apiVersion: v1
kind: Secret                      # kind is secret instead of configmap
metadata:
  name: sample-next-app-secret
  labels:
    app: sample-next-app         # till this block, same as configmap.yaml
stringData:                      # It's stringData instead of data. This is because we are storing sensitive data in the secret.yaml file. ( base64 encodede )
  DB_HOST: "db.default.svc.cluster.local"       # some dummy data
  DB_PASSWORD: "fiw86f734fuh8"
  DB_PORT: "5432"
type: Opaque                      # for generic key-value secrets, it's type Opaque